name: mrcope_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas
      - numpy
      - matplotlib
      - seaborn
      - scipy

  - r-base=4.2
  - r-devtools
  - r-remotes        
  - r-optparse
  - r-tidyverse
  - r-qqman
  - r-ggrepel
  - r-data.table
  - r-patchwork
  - r-rcolorbrewer
  - r-mass
  - r-matrix
  - r-gridextra
  - r-lattice
  - r-stringr
  - r-purrr
  - r-plyr
  - r-tidyr
